# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir L:/Xilinx_Training/Lab5/genLoops.cache/wt [current_project]
set_property parent.project_path L:/Xilinx_Training/Lab5/genLoops.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo l:/Xilinx_Training/Lab5/genLoops.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/Xilinx_Training/Lab2/concurrency.srcs/sources_1/new/LED_manager.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/KCU105/meta_harden.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/Xilinx_Training/Lab1/useTools.srcs/sources_1/new/register8.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/KCU105/reset_bridge.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/KCU105/uart_baud_gen.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/KCU105/uart_rx.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/KCU105/uart_rx_ctl.vhd
  L:/Xilinx_Training/Lab5/genLoops.srcs/sources_1/imports/KCU105/uart_led.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top uart_led -part xc7z020clg484-1 -no_iobuf


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_led.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uart_led_utilization_synth.rpt -pb uart_led_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
